package com.cts.communication;

public enum ResponseValues {
	
	SUCCESS, ERROR, UNKNOWN, EMPTYEMAILFIELD, EMPTYPASSWORDFIELD, INVALIDEMAILFORMAT, DBERROR,
	LOGININVALIDCREDENTIALS,
	REGISTERSUCCESS, REGISTEREMPTYTITLE, REGISTEREMPTYFIRSTNAMEFIELD, REGISTEREMPTYLASTNAMEFIELD, REGISTEREXISTINGEMAIL, 
	RECOVERYSUCCESS, RECOVERYINCORRECTEMAIL,
	TICKETEMPTYSUBJECTFIELD, TICKETNOCATEGORYSELECTED, TICKETEMPTYDESCRIPTIONFIELD, TICKETEMPTYCOMMENTFIELD

}
