package com.cts.communication;

public enum ResponseValues {
	
	SUCCESS, EMPTYUSERID, EMPTYTITLE, EMPTYFIRSTNAME, EMPTYLASTNAME, EMPTYEMAIL, EMPTYPASSWORD, INVALIDEMAILFORMAT, DBERROR, UNKNOWN,
	LOGININVALIDCREDENTIALS,
	REGISTERSUCCESS, REGISTEREXISTINGEMAIL, 
	RECOVERYSUCCESS, RECOVERYINCORRECTEMAIL,
	TICKETEMPTYSUBJECT, TICKETEMPTYCATEGORY, TICKETEMPTYDESCRIPTION, TICKETEMPTYCOMMENT,
	UPDATEUSERSUCCESS, UPDATEUSEREMPTYOLDPASSWORD, UPDATEUSEREMPTYNEWPASSWORD, UPDATEUSERPASSWORDSNOTMATCHING,
	CATEGORYEMPTYID, CATEGORYEMPTYNAME,
	ROOTMANAGEMENTEMPTYSYSADMIN
}
